sudo: required
services:
  - docker

before_install:
  - docker build -t mikezank/ngfront -f Dockerfile.dev . 

script:
  - docker run mikezank/ngfront ng test --no-watch --no-progress --code-coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "ngfront"
  env: "Ngfront-env"
  bucket_name: "elasticbeanstalk-us-east-1-187377688853"
  bucket_path: "ngfront"
  on:
    branch: master



  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
