sudo: required
services:
  - docker

before_install:
  - docker build -t mikezank/ngfront -f Dockerfile.dev . 

script:
  - docker run mikezank/ngfront ng test --no-watch --no-progress --code-coverage
