FROM node as builder

WORKDIR /app

COPY package.json .
RUN npm install
RUN npm install -g @angular/cli@latest

COPY . /app

RUN ng build --prod

# PROD environment
FROM nginx:alpine
COPY --from=builder /app/dist/ngdev /usr/share/nginx/html
